### ISSUE TITLE
Enhance Fourier Sum Graphic

### ISSUE THREAD

**Issue by ferjjp** [marvelek/matsup-2015c2-tp-fourier#1]
Actualmente el grafico resultante de la serie de fourier salta en una ventana nueva, porque esta hecha con ezplot. La idea es que quede como estaba antes, habria que fijarse en el codigo de antes y ver que es rescatable de eso, pero lo principal es que se vea TODO un periodo, y que plotee donde debe plotear.

**Comment by marvelek** [comment]
Ya está en la misma ventana y muestra varios períodos.
